export enum RequestStatus {
  PENDING_SYNC = 'PENDING_SYNC',
  WAITING_MANAGER_APPROVAL = 'WAITING_MANAGER_APPROVAL',
  APPROVED = 'APPROVED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLATION_PENDING = 'CANCELLATION_PENDING',
  CANCELLED = 'CANCELLED',
}
